name: JPMS Experiment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build with Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - '11'
          - '17'

    steps:
    - name: Checkout sourcecode
      uses: actions/checkout@v2

    - name: Cache Local Maven Repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'

    - name: Build
      run: mvn clean package
